# Data Preprocessing Tools

In [1]:
import numpy as pd
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# Load Data
df = pd.read_csv('Loan_application.csv')
df.head()

Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0

In [3]:
# check the missing
df.isnull().sum()

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64

In [4]:
# Define Dep and Indep variables
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
x

array([[   19, 19000,     0,     2],
       [   35, 20000,     0,     2],
       [   26, 43000,     0,     0],
       ...,
       [   50, 20000,     0,     3],
       [   36, 33000,     0,     0],
       [   49, 36000,     1,     1]], dtype=int64)

In [5]:
# Train/ Test Split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=9)

In [6]:
x_train

array([[    28,  84000,      1,      2],
       [    21,  72000,      1,      0],
       [    39,  71000,      0,      2],
       ...,
       [    42,  65000,      0,      2],
       [    39,  77000,      1,      1],
       [    44, 139000,      1,      2]], dtype=int64)

In [7]:
# Feature Scalling
ss = StandardScaler()
x_train[:,[0,1]] = ss.fit_transform(x_train[:,[0,1]] )
x_test[:,[0,1]] = ss.transform(x_test[:,[0,1]])
x_train

array([[ 0,  0,  1,  2],
       [-1,  0,  1,  0],
       [ 0,  0,  0,  2],
       ...,
       [ 0,  0,  0,  2],
       [ 0,  0,  1,  1],
       [ 0,  2,  1,  2]], dtype=int64)

# Making Model

In [8]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
results = LogisticRegression(random_state=0)
results.fit(x_train,y_train)

LogisticRegression(random_state=0)

# Evaluation Metric (F1-Score)

In [9]:
from sklearn.metrics import *

In [10]:
y_pred = results.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[34,  9],
       [ 6, 31]], dtype=int64)

In [12]:
accuracy_score(y_test,y_pred)

0.8125

In [13]:
recall_score(y_test,y_pred)

0.8378378378378378

In [14]:
f1_score(y_test,y_pred)

0.8051948051948052

In [15]:
import pickle

In [16]:
pickle.dump(results,open("savemodel.pkl","wb"))

In [17]:
#Let install gradio first
!pip install gradio

Defaulting to user installation because normal site-packages is not writeable


In [18]:
#read and  our model and use the saved model

In [19]:
my_model=pickle.load(open("savemodel.pkl","rb"))

In [20]:
#Checking the model save

In [21]:
#let create function that accept inputs and make prediction
def make_prediction(Age,Salary,Education,Capital):#initializing the fanction making prediction using the real save model
    y_pred=my_model.predict([[Age,Salary,Education,Capital]])
    if y_pred>0:
        output='Congz you are not eligible for the loan'
    else:
        output='sorry you are not eligible for the loan'
        return output

In [22]:
import gradio as gr 

In [23]:
import sys
print(sys.executable)

C:\Program Files\anaconda\1\python.exe


In [24]:
import gradio as gr

def make_prediction(age, salary, education, capital):
    # Example function to process inputs and return an output
    return f"Age: {age}, Salary: {salary}, Education: {'Graduated' if education == 1. else 'Not Graduated'}, Capital: {capital}"

Age = gr.Number(label='Enter your Age')
Salary = gr.Slider(0, 200000, label='Enter your Salary')
Education = gr.Radio([1., 0.], label='Select your Education (1 for Graduated, 0 for Not Graduated)')
Capital = gr.Number(label='Enter your Capital')
output = gr.TextArea()

interface = gr.Interface(fn=make_prediction, inputs=[Age, Salary, Education, Capital], outputs=output)
interface.launch(share=True)

* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://f928e8962cb1edd234.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
