In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import*

In [102]:
data=pd.read_csv('Loan_application.csv')

In [104]:
print(data.head())

   Age  Salary  Education  Capital  Loan
0   19   19000          0        2     0
1   35   20000          0        2     0
2   26   43000          0        0     0
3   27   57000          0        0     0
4   19   76000          1        0     0


In [106]:
print(data.isnull().sum())

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64


In [108]:
print(data.dropna())

     Age  Salary  Education  Capital  Loan
0     19   19000          0        2     0
1     35   20000          0        2     0
2     26   43000          0        0     0
3     27   57000          0        0     0
4     19   76000          1        0     0
..   ...     ...        ...      ...   ...
395   46   41000          1        3     0
396   51   23000          0        4     0
397   50   20000          0        3     0
398   36   33000          0        0     0
399   49   36000          1        1     0

[400 rows x 5 columns]


In [110]:
print(data.isnull().sum())

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64


In [112]:
print(data.fillna('1'))

     Age  Salary  Education  Capital  Loan
0     19   19000          0        2     0
1     35   20000          0        2     0
2     26   43000          0        0     0
3     27   57000          0        0     0
4     19   76000          1        0     0
..   ...     ...        ...      ...   ...
395   46   41000          1        3     0
396   51   23000          0        4     0
397   50   20000          0        3     0
398   36   33000          0        0     0
399   49   36000          1        1     0

[400 rows x 5 columns]


In [114]:
print(data.isnull().sum())

Age          0
Salary       0
Education    0
Capital      0
Loan         0
dtype: int64


In [124]:
x = data.iloc[:,:-1].values
y=data.iloc[:,-1].values
x

array([[   19, 19000,     0,     2],
       [   35, 20000,     0,     2],
       [   26, 43000,     0,     0],
       ...,
       [   50, 20000,     0,     3],
       [   36, 33000,     0,     0],
       [   49, 36000,     1,     1]], dtype=int64)

In [126]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

In [130]:
ss=StandardScaler()
x_train[:,[0,1]]=ss.fit_transform(x_train[:,[0,1]])
x_test[:,[0,1]]=ss.transform(x_test[:,[0,1]])
x_train

array([[0, 1, 1, 0],
       [0, 0, 1, 4],
       [0, 0, 0, 2],
       ...,
       [0, 2, 1, 1],
       [1, 2, 1, 0],
       [0, 0, 1, 4]], dtype=int64)

In [138]:
results=LogisticRegression(random_state=0)
results.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [150]:
y_pred=results.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [152]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[39, 13],
       [ 2, 26]], dtype=int64)

In [166]:
accuracy_score(y_test,y_pred)

0.8125

In [172]:
recall=recall_score(y_test,y_pred)
recall

0.9285714285714286

In [176]:
f1_score(y_test,y_pred)

0.7761194029850746

In [178]:
import pickle

In [185]:
pickle.dump(results,open("savedmodel_2.pkl","wb"))

In [189]:
my_model=pickle.load(open("savedmodel_2.pkl","rb"))
my_model

LogisticRegression(random_state=0)

In [191]:
def make_prediction(Age,Salary,Education,Capital):
    y_pred =my_model.predict([[Age, Salary, Education, Capital]])

    if y_pred>0:
        output='congs you are eligible for the loan'
    else:
        output='you are not eligible for the loan'
    return output

In [195]:
import gradio as gr
Age=gr.Number(label='enter your age')
Salary=gr.Slider(0,200000,label='enter your salary')
Education=gr.Radio([1.0,0.0],label='select your education')
Capital=gr.Number(label="enter the capital")
output=gr.TextArea()
interface=gr.Interface(fn=make_prediction,inputs=[Age,Salary,Education,Capital],outputs=output)
interface.launch(share=True)

* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://b3047620f181ff2928.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
